### ISSUE TITLE
set up redundancy

### ISSUE THREAD

**Issue by joshnortheimer** [bitfocus/companion-satellite#36] opened 2022-01-28 20:54 UTC
would it be possible to add an option in the context menu for a secondary/backup IP address? that way, if the satellite install loses connection to the main companion install, it can try a different computer automatically. that would allow us to create a backup companion set up, and switch over on failure.  thanks!

**Comment by Julusian** [comment] 2022-01-28 21:07
Duplicate of #11

**Closed by Julusian** 2022-01-28 21:07 UTC
