### ISSUE TITLE
Using Companion Satellite with the Streamdeck-app Companion-plugin

### ISSUE THREAD

**Issue by Mattis-J** [bitfocus/companion-satellite#137] opened 2024-07-07 14:11 UTC
Hello everyone,

I need some help with an issue I encountered using Companion Satellite. We're a radio and television station in Emmen, Drenthe. And we use Companion a lot to control a lot of systems with just a simple button click.

Because we're starting to use the trigger option of Companion, we want to move the application to a dedicated server in our server room. We've setup the application and I hoped Companion Satellite would do the trick, but sadly it doesn't. When we installed our Companion-application we've chosen to let the Companion buttons be inserted via the Streamdeck-application. This is because we use the hotkey option of the Streamdeck-app to control CasparCG. 

I hoped Satellite would also work with this option, but unfortunately it doesn't. Does anybody know a fix around this or is this maybe a good feature to add to the application?
 
 Thanks in advance!
 
 Mattis

**Comment by Julusian** [comment] 2024-07-20 20:28
Satellite doesn't support the elgato software plugin.  

> This is because we use the hotkey option of the Streamdeck-app to control CasparCG.

you could do that through companion, I don't remember if there is a module for the casparcg-client, but viceo-hotkey will allow you to trigger the hotkeys. 

This is a duplicate of #29

**Closed by Julusian** 2024-07-20 20:28 UTC
