### ISSUE TITLE
Rasperry image has no LAN drivers?

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-satellite#46] opened 2022-08-17 09:01 UTC
This might be a stupid question, so I am sorry in advance, but when i install the Pi image to my 1B+ the LAN port doesn'T work.

So I was wondering if the Pi image maybe is missing the NIC drivers?

**Comment by Julusian** [comment] 2022-08-17 13:44
I'm surprised that the pi image boots at all on a 1!
The image is built for arm64, which should only work on a 3/4 (maybe a 2?), but I cant vouch for the reliability of anything below a 4. It may or may not have the same usb reliability issues experienced with companion-pi.

That said, I am running a couple of non-streamdeck devices off a zero-w2. I am having issues with wifi, but I think that is unrelated to satellite or the usb device connected.
I don't think I am using the satellite image currently for it, I think I installed it before making the image

**Comment by DachsbauTV** [comment] 2022-08-20 09:15
Thanks @Julusian for the reply. 

Would it be possible to install companion satellite under the rasperryOS? 
The OS works fine, incl. the nic, so if i could install it under the OS it might even work :)

**Comment by Julusian** [comment] 2022-10-09 22:18
The image is raspberrypi os, but the 64bit version. That image shouldnt have booted at all on that model, as its not a 64bit cpu..

It is possible to install manually on the 32bit os, but from memory running nodejs on the pi 1 was tricky, as noone builds or distributes it for armv6 (most places do armv7)
There are some rough steps in the readme https://github.com/bitfocus/companion-satellite#manual-headless--raspbrry-pi.

Im going to close this, as this is kind of by design, or hopefully you managed to figure something out

**Closed by Julusian** 2022-10-09 22:18 UTC
